DELETE  http://localhost:3001/api/movies/5ef4755b7fd656469495c9da
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpaXR1cyIsImlkIjoiNWVmNDcyY2U4NGNlZTY0ODM0MWFmZTJkIiwiaWF0IjoxNTkzMDc4NTU2fQ.IzmWXt5AQEaydHm5Q_QSWsCJu5ahfOarIWgltp7GEvo

//Janecky
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZTNkYTdlNzZkZDAzNWE0MDE2MTI3ZiIsImlhdCI6MTU5MjA0NDAwMX0.7Hb_Nd5MiOR2oPJqf2l5KAXyWJWXtt6g5kpiLI5x1Fs


//Kiitus
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZTNiZmEyOGQ1YjZkMTBmNDJhZGJmNiIsImlhdCI6MTU5MTk5MDE4N30.DajSHna3cBvrrOs7VX_Mrg25j5XpD0G8FG5_TGVO0D8